### ISSUE TITLE
HealthcheckWebServices should call analyticsManager.getHealthChecks()

### ISSUE THREAD

**Issue by Jean-MichelForhan-KLEE** [KleeGroup/vertigo#128]
Currently, this webservice returns only "OK" which meains that all projects need to define project specific webservice to get monitoring information from analyticsManager.

This should be standard.

**Comment by mlaroche** [comment]
This kind of webserice already exists in this class : https://github.com/KleeGroup/vertigo/blob/master/vertigo-vega-impl/src/main/java/io/vertigo/vega/engines/webservice/cmd/ComponentCmdWebServices.java

But handle with care and use this **only** in a **developpement** envrionnement because those webservices are not secured (@AnonymousAccessAllowed)
If a project need's it you need to implement it in your project (you can just use the given class as an example)

**Comment by mlaroche** [comment]
You're right, added it for consistency. The warning for handle with care is still valid!
